apiVersion: batch/v1
kind: Job
metadata:
  name: oneshot-parallel
spec:
  parallelism: 5
  completions: 10
  template:
    metadata:
      labels:
        name: oneshot-parallel
    spec:
      containers:
      - args:
        - --keygen-enable
        - --keygen-exit-on-complete
        - --keygen-num-to-gen
        - "10"
        image: gcr.io/kuar-demo/kuard-amd64:1
        name: oneshot
      restartPolicy: OnFailure

